spring:
  #db 설정
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://localhost:3306/REALPT?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:h2:tcp://localhost/~/ecommerce
    username: sa
    password:

  #jpa 설정
  jpa:
    show-sql: true
    hibernate.ddl-auto: create


